title: Jak přidat kurz na Nauč se Python
description: Návod na přidání kurzu na Nauč se Python
long_description: |

  V tomto meta-kurzu je kompletní návod na přidávání kurzů na Nauč se Python.

  Kurz je určený pro organizátory a k přidání kurzu jsou potřeba jen základní znalosti práce
  s gitem a GitHubem.
canonical: true
meta: true
sessions:
- title: Přidání kurzu
  slug: adding-a-run
  materials:
  - lesson: meta/local-run
  - lesson: meta/submitting-a-run

extra_lessons:
- git/install
- git/branching
- git/git-collaboration-2in1
- beginners/install
- beginners/cmdline
- beginners/venv-setup
- intro/notebook
- fast-track/yaml
